  CREATE TABLE "DESAFIO"."USUARIO" 
   (	"NOME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"SENHA" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	 CONSTRAINT "USUARIO_PK" PRIMARY KEY ("EMAIL");
	 
CREATE TABLE "DESAFIO"."TELEFONE" 
   (	"NUMERO" NUMBER NOT NULL ENABLE, 
	"ID" NUMBER NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"DDD" NUMBER(2,0) NOT NULL ENABLE, 
	"TIPO" VARCHAR2(10 BYTE), 
	 CONSTRAINT "TELEFONE_PK" PRIMARY KEY ("ID")
	 CONSTRAINT "USUARIO_FK" FOREIGN KEY ("EMAIL") ENABLE
	  REFERENCES "DESAFIO"."USUARIO" ("EMAIL") ENABLE